import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, League_Spartan } from "next/font/google";
import ActiveSectionContextProvider from "@/context/active-section-context";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer";
import ThemeSwitch from "@/components/themeSwitch";
import ThemecontextProvider from "@/context/theme-context";

const inter = Inter({ subsets: ["latin"] });
const league = League_Spartan({
  subsets: ["latin"],
  variable: "--league-spartan",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Shivam | Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`bg-slate-50 text-gray-900 relative pt-28 sm:pt-36 
        dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90${league.variable}`}
      >
        <div
          className="bg-[#fffcd9] absolute -z-10 top-[-6rem] right- [10rem] h-[30rem] w-[20rem] rounded-full blur-[10rem]
        sm:w-[68rem] dark:bg-[#946263]"
        ></div>
        <div
          className='bg-[#dbd7fb] absolute -z-10 top-[-1rem] left-[-35rem] h-[30rem] w-[50rem] rounded-full blur-[10rem]
        sm:w-[68rem] md:left-[-33rem] lg"left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]'
        ></div>
        <ThemecontextProvider>
          <ActiveSectionContextProvider>
            <Header />
            {children}
            <Footer />
            <Toaster position="top-right" />
            <ThemeSwitch />
          </ActiveSectionContextProvider>
        </ThemecontextProvider>
      </body>
    </html>
  );
}
